### ISSUE TITLE
`FgaRequiredParamError` is inconsistent

### ISSUE THREAD

**Issue by miparnisari** [openfga/dotnet-sdk#15]
This code

```c#
var configuration = new ClientConfiguration() {
                    ApiHost = "api.us1.fga.dev",
                };
var fgaClient = new OpenFgaClient(configuration);
var response = await fgaClient.ReadAuthorizationModels();
Console.WriteLine(response);
```

produces

```
OpenFga.Sdk.Exceptions.FgaRequiredParamError: 'Required parameter StoreId was not defined when calling Configuration.'
```

I expected: 

```
OpenFga.Sdk.Exceptions.FgaRequiredParamError: 'Required parameter StoreId was not defined when calling ReadAuthorizationModels.'
```

See https://github.com/openfga/dotnet-sdk/blob/ee392895d5159618085db84aedb990d261332b90/src/OpenFga.Sdk/Api/OpenFgaApi.cs#L109

**Comment by rhamzeh** [comment]
Will make this change, but it is kind of tricky, considering StoreId is defined in the configuration and not at the method level. I'll make it and if others find it confusing, we can change it then.

Thanks!
