### ISSUE TITLE
[v2.2] ClientListObjectsRequest.ContextualTuples property has wrong Type

### ISSUE THREAD

**Issue by xXAvoraXx** [openfga/dotnet-sdk#17]
Hello, I am reviewing the OpenFgaClient source codes while migrating my v2.1 codes to v2.2. I saw that the ContextualTuples property in the ClientListObjectsRequest class is List<TupleKey>, it should be ClientTupleKey.

![image](https://user-images.githubusercontent.com/6988989/231588229-ee47ccb9-c4b0-43a4-8b5f-64fb6c63d999.png)

**Comment by rhamzeh** [comment]
Thanks for the report @xXAvoraXx! We'll have a fix early in the morning in v0.2.3

**Comment by xXAvoraXx** [comment]
Tuples sent to the Listobjects endpoint (.net SDKS 2.2) give an invalid tuple key error.

"grpc_code":2027,"error":"rpc error: code = Code(2027) desc = Invalid tuple ''. Reason: the 'user' field is malformed"}
