### ISSUE TITLE
ListObject returns 1000 objects

### ISSUE THREAD

**Issue by abmptit** [openfga/dotnet-sdk#29]
I noticed that ListObjects return 1000 records.
How Can I remove this limit please ?

`public async Task<IEnumerable<int>> GetCanReadScope(string username)
        {
            var fgaClient = new OpenFgaClient(_clientConfiguration);
            var body = new ClientListObjectsRequest() {
                User = $"user:{username}",
                Type = "survey",
                Relation = "can_read"

            };
            var response = await fgaClient.ListObjects(body);
            return response.Objects.Select(x => int.Parse(x.Replace("survey:", "")));
        }`

**Comment by rhamzeh** [comment]
Hi @abmptit 

Are you using this with a locally hosted OpenFGA server? In that case you would need to override the `listObjectsMaxResults` on the OpenFGA server itself (See: https://github.com/openfga/openfga/blob/main/.config-schema.json#L52-L58)

You can use: the `OPENFGA_LIST_OBJECTS_MAX_RESULTS` environment variable
