### ISSUE TITLE
Support passing of storeId as a parameter

### ISSUE THREAD

**Issue by lorenlew** [openfga/dotnet-sdk#33]
Currently it is only possible to set storeId in OpenFgaClient property.

Would it be possible to pass it as part of the "options" object for the method (Check, List, etc), same as it is done for AuthorizationModelId?

It would be nice to be able to target multiple stores from the code and have OpenFgaClient as singleton in DI.

**Comment by rhamzeh** [comment]
Hi @lorenlew. Absolutely! That's where we're heading but it requires a few breaking changes, which we want to make.

We're streamlining this interface in our Java SDK and bringing it to the rest of the SDKs soon.

Expect some breaking changes soon, but hopefully the outcome will be better DX.
