### ISSUE TITLE
Export Metrics

### ISSUE THREAD

**Issue by ewanharris** [openfga/dotnet-sdk#68]
### Checklist

- [X] I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).

### Describe the problem you'd like to have solved

As a consumer of the SDK, I would like to hook it to my dashboards to get data on several metrics.

### Describe the ideal solution

Integrate the OpenTelemetry .NET API package https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md

We need to be able to expose the metrics as outlined in the [JS](https://github.com/openfga/js-sdk/pull/117) and [Python](https://github.com/openfga/python-sdk/pull/107) SDKs

**Comment by Hawxy** [comment]
Worth mentioning that OTEL's HttpClient instrumentation already covers a handful of metrics you're looking at collecting:
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.Http/README.md

A number of these metrics are baked into .NET 8+ as well: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-system-net
